package main;

import data.Datamanager;
import java.awt.BorderLayout;

/**
 *
 * @author arnoud
 */
public class MainWindow extends javax.swing.JFrame 
    {
    private final Datamanager datamanager;
    
    private final MonitorMainPanelGraph graphPanel;
    
    public MainWindow(Datamanager _datamanager) 
        {
        datamanager = _datamanager;    
            
        initComponents();
        
        graphPanel = new MonitorMainPanelGraph(datamanager);
        centre_PN.add(graphPanel, BorderLayout.CENTER);
        }

    //=====================================================================
    //=====================================================================
    //=====================================================================
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_PN = new javax.swing.JPanel();
        top_PN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centre_PN = new javax.swing.JPanel();
        bottom_PN = new javax.swing.JPanel();
        exit_BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(java.awt.Color.white);

        main_PN.setBackground(java.awt.Color.white);
        main_PN.setLayout(new java.awt.BorderLayout());

        top_PN.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Mainwindow");

        javax.swing.GroupLayout top_PNLayout = new javax.swing.GroupLayout(top_PN);
        top_PN.setLayout(top_PNLayout);
        top_PNLayout.setHorizontalGroup(
            top_PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        top_PNLayout.setVerticalGroup(
            top_PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_PNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        main_PN.add(top_PN, java.awt.BorderLayout.NORTH);

        centre_PN.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout centre_PNLayout = new javax.swing.GroupLayout(centre_PN);
        centre_PN.setLayout(centre_PNLayout);
        centre_PNLayout.setHorizontalGroup(
            centre_PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        centre_PNLayout.setVerticalGroup(
            centre_PNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        main_PN.add(centre_PN, java.awt.BorderLayout.CENTER);

        exit_BT.setText("Exit");
        exit_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_BTActionPerformed(evt);
            }
        });
        bottom_PN.add(exit_BT);

        main_PN.add(bottom_PN, java.awt.BorderLayout.SOUTH);

        getContentPane().add(main_PN, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //=====================================================================
    //=====================================================================
    //=====================================================================
    
    private void exitWindow()
        {
        this.dispose();
        System.exit(0);
        }
    
    //=====================================================================
    //=====================================================================
    //=====================================================================
    
    private void exit_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_BTActionPerformed
        exitWindow();
    }//GEN-LAST:event_exit_BTActionPerformed

    //=====================================================================
    //=====================================================================
    //=====================================================================
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom_PN;
    private javax.swing.JPanel centre_PN;
    private javax.swing.JButton exit_BT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main_PN;
    private javax.swing.JPanel top_PN;
    // End of variables declaration//GEN-END:variables
}
